user: 
    account:
        username: 
        password: 

streamers:
   INnoVation天下第一人吕布人族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/innovation_s2
#         - https://www.huya.com/igxy520
      picture_path: picture/INnoVation.png
#      picture_path: E:/bilibili/bilibili/picture/INnoVation.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - INnoVation
         - 人族
   # Alphaxsc2比赛解说频道星际2:
   #    url:
   #       - http://play.afreecatv.com/alphaxsc2/null
   #    picture_path: picture/AlphaX.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - AlphaX
   #       - 比赛
   #       - 解说录像
   Rogue脑虫虫族天梯第一视角星际2:
      tid: 171
      url:
         - http://play.afreecatv.com/bau6660
      picture_path: picture/Rogue.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Rogue
         - 虫族
   ByuN人族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/sc2byun
      picture_path: picture/ByuN.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - ByuN
         - 人族
   soO直播录像输本虫族天梯第一视角星际2:
      tid: 171
      url:
         - https://play.afreecatv.com/djdbstn
      picture_path: picture/soO.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - soO
         - 虫族
   sOs直播录像狗哥神族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/jinairsos1
      picture_path: picture/sOs.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - sOs
         - 神族
   Stats直播录像拔本神族天梯第一视角星际2:
      tid: 171
      url:
         - https://play.afreecatv.com/kimdaeyeob11
      picture_path: picture/Stats.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Stats
         - 神族
   Dark直播录像暗本虫族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/qkrfuddn0
      picture_path: picture/Dark.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Dark
         - 虫族
   Maru直播录像人族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/maru072
      picture_path: picture/Maru.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Maru
         - 人族
   TY直播录像全教主全太阳人族天梯第一视角星际2:
      tid: 171
      url:
         - https://play.afreecatv.com/sunstar1994
      picture_path: picture/TY.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - TY
         - 人族
   # Zest直播录像神族天梯第一视角星际2:
   #    url:
   #       - https://www.twitch.tv/sc2_zest
   #    picture_path: picture/Zest.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - Zest
   #       - 神族
   PartinG直播录像跳跳胖丁神族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/partingthebigboy
      picture_path: picture/PartinG.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - PartinG
         - 神族
   SHOWTIME直播录像神族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/sc2showtime
      picture_path: picture/SHOWTIME.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - SHOWTIM
         - 神族
   # Serral直播录像虫族天梯第一视角星际2:
   #    url:
   #       - https://www.twitch.tv/serral
   #    picture_path: picture/Serral.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - Serral
   #       - 虫族
   Solar直播录像虫族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/sc2solar
      picture_path: picture/Solar.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Solar
         - 虫族
   UThermal直播录像常威打人族天梯第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/liquidthermy
      picture_path: picture/UThermal.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - UThermal
         - 人族
   # XY直播录像鸟哥游戏大厅天梯第一视角星际2:
   #    url:
   #       - https://www.huya.com/igxy520
   #    picture_path: picture/XY.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - XY
   #       - 人族
   # TIME直播录像开酒人族第一视角星际2:
   #    url:
   #       - https://www.douyu.com/1858651
   #    picture_path: picture/TIME.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - TIME
   #       - 人族
   HeroMaRinE直播录像河马披萨人皇人族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/heromarine
      picture_path: picture/HeroMarine.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - HeroMarine
         - 人族
   Harstem直播录像神族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/harstem
      picture_path: picture/Harstem.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Harstem
         - 神族
   # printf直播录像地堡王神族第一视角星际2:
   #    url:
   #       - https://www.twitch.tv/quasarprintf
   #    picture_path:
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - printf
   #       - 神族
   # SuperNova直播录像人族第一视角星际2:
   #    url:
   #       - https://www.twitch.tv/root_supernova
   #    picture_path: picture/SuperNova.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - SuperNova
   #       - 人族
   Trap直播录像扛旗人神族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/trap321
      picture_path: picture/Trap.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Trap
         - 神族
   Cure直播录像人族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/dpgcure
      picture_path: picture/Cure.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Cure
         - 人族
   # Stephano直播录像虫族第一视角星际2:
   #    url:
   #       - https://www.twitch.tv/gostephano
   #    picture_path: picture/Stephano.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - Stephano
   #       - 虫族
   # RagnaroK直播录像虫族第一视角星际2:
   #    url:
   #       - https://www.twitch.tv/SC2_Ragnarok
   #    picture_path: picture/RagnaroK.png
   #    tag:
   #       - 星际争霸2
   #       - 虚空之遗
   #       - 第一视角
   #       - RagnaroK
   #       - 虫族
   Clem直播录像人族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/clem__sc2
      picture_path: picture/Clem.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - clem
         - 人族
   Reynor直播录像虫族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/rb_reynor
      picture_path: picture/reynor.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Reynor
         - 虫族
   MaxPax直播录像神族第一视角星际2:
      tid: 171
      url:
         - http://www.twitch.tv/maxpaxsc2
      picture_path:
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Maxpax
         - 神族
   Dream梦本直播录像人族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/dream_sc2
      picture_path: picture/dream.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Dream
         - 人族
   Cyan探机鸡哥直播录像神族第一视角星际2:
      tid: 171
      url:
         - https://www.douyu.com/5718
      picture_path: picture/cyan.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Cyan
         - 神族
   Scarlett噶姐直播录像虫族星际1星际2:
      tid: 171
      url:
         - https://www.twitch.tv/scarlettm
      picture_path: picture/scarlett.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - Scarlett
         - 虫族
   Cloudy茂神直播录像神族第一视角星际2:
      tid: 171
      url:
         - https://www.huya.com/cloudy
      picture_path: picture/cloudy.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - cloudy
         - 神族
   Zoun直播录像神族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/zoun123
      picture_path: picture/zoun.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - zoun
         - 神族
   Special肥宅直播录像人族第一视角星际2:
      tid: 171
      url:
         - https://www.twitch.tv/special_
      picture_path: picture/special.png
      tag:
         - 星际争霸2
         - 虚空之遗
         - 第一视角
         - special
         - 人族