user_name: 18616533246
pass_word: whosyourdaddy

chromedrive_path: /root/bilibiliupload/chromedriver

links_id:
    Hero Marine直播录像小天才人族第一视角星际2:
        - https://www.twitch.tv/heromarine
    lamboking直播录像宝岛双神神族第一视角星际2:
        - https://www.twitch.tv/lamboking
    special直播录像墨西哥毒枭人族第一视角星际2:
        - https://www.twitch.tv/special_
    stephano直播录像墨西哥毒枭人族第一视角星际2:
        - https://www.twitch.tv/gostephano
