user_name: 18616533246
pass_word: whosyourdaddy

chromedrive_path: /root/bilibiliupload/chromedriver

links_id:
    【INnoVation直播录像】天下第一人吕布人族天梯第一视角星际2:
        - https://www.twitch.tv/innovation_s2
    【soO直播录像】输本虫族天梯第一视角星际2:
        - https://www.twitch.tv/sc2soo
    【sOs直播录像】狗哥$o$神族天梯第一视角星际2:
        - https://www.twitch.tv/jinairsos1
    【Stats直播录像】拔本神族天梯第一视角星际2:
        - https://www.twitch.tv/kimdaeyeob3
    【Dark直播录像】暗本虫族天梯第一视角星际2:
        - https://www.twitch.tv/qkrfuddn0
    【Scarlett直播录像】噶姐虫族天梯第一视角星际2:
        - https://www.twitch.tv/scarlettm
    【Maru直播录像】人族天梯第一视角星际2:
        - https://www.twitch.tv/maru072
    【TY直播录像】全教主全太阳人族天梯第一视角星际2:
        - https://www.twitch.tv/sc2tyty
    【Zest直播录像】神族天梯第一视角星际2:
        - https://www.twitch.tv/sc2_zest
    【PartinG直播录像】跳跳胖丁神族天梯第一视角星际2:
        - https://www.twitch.tv/partingthebigboy
    【Rogue直播录像】脑虫虫族天梯第一视角星际2:
        - https://www.twitch.tv/roguejinair
    【SHOWTIME直播录像】ID克星第一视角星际2:
        - https://www.twitch.tv/sc2showtime
    【serral直播录像】虫王虫族天梯第一视角星际2:
        - https://www.twitch.tv/serral
    【Solar直播录像】虫族天梯第一视角星际2:
        - https://www.twitch.tv/sc2solar
    【UThermal直播录像】常威打人族天梯第一视角星际2:
        - https://www.twitch.tv/liquidthermy       
    【XY直播录像】不务正业的鸟哥游戏大厅天梯乱七八糟的游戏第一视角星际2:
        - https://www.huya.com/igxy520
    【TIME直播录像】开酒人族第一视角星际2:
        - https://www.douyu.com/1858651       
