user_name: 18616533246
pass_word: whosyourdaddy

chromedrive_path: /root/bilibiliupload/chromedriver

links_id:
    INnoVation直播录像天下第一人吕布人族天梯第一视角星际2:
        - https://www.twitch.tv/innovation_s2
    soO直播录像输本虫族天梯第一视角星际2:
        - https://www.twitch.tv/sc2soo
    sOs直播录像狗哥神族天梯第一视角星际2:
        - https://www.twitch.tv/jinairsos1
    Stats直播录像拔本神族天梯第一视角星际2:
        - https://www.twitch.tv/kimdaeyeob3
    Dark直播录像暗本虫族天梯第一视角星际2:
        - https://www.twitch.tv/qkrfuddn0
    Maru直播录像人族天梯第一视角星际2:
        - https://www.twitch.tv/maru072
    TY直播录像全教主全太阳人族天梯第一视角星际2:
        - https://www.twitch.tv/sc2tyty
    Zest直播录像神族天梯第一视角星际2:
        - https://www.twitch.tv/sc2_zest
        - http://bj.afreecatv.com/sc2zest
    PartinG直播录像跳跳胖丁神族天梯第一视角星际2:
        - https://www.twitch.tv/partingthebigboy
    Rogue直播录像脑虫虫族天梯第一视角星际2:
        - https://www.twitch.tv/roguejinair
    SHOWTIME直播录像ID克星第一视角星际2:
        - https://www.twitch.tv/sc2showtime
    serral直播录像虫王虫族天梯第一视角星际2:
        - https://www.twitch.tv/serral
    Solar直播录像虫族天梯第一视角星际2:
        - https://www.twitch.tv/sc2solar
    UThermal直播录像常威打人族天梯第一视角星际2:
        - https://www.twitch.tv/liquidthermy
    XY直播录像不务正业的鸟哥游戏大厅天梯乱七八糟的游戏第一视角星际2:
        - https://www.huya.com/igxy520123
    TIME直播录像开酒人族第一视角星际2:
        - https://www.douyu.com/1858651
    Hero Marine直播录像小天才人族第一视角星际2:
        - https://www.twitch.tv/heromarine
    nice直播录像宝岛双神神族第一视角星际2:
        - https://www.twitch.tv/sc2nice
    special直播录像墨西哥毒枭人族第一视角星际2:
        - https://www.twitch.tv/special_
